### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by soichih** [kitchell/app-generatetractsurfaces#2]
I am seeing following error messages from couple of instances of this app.

```
16.60user 2.31system 1:22.25elapsed 23%CPU (0avgtext+0avgdata 154812maxresident)k
0inputs+195568outputs (0major+183195minor)pagefaults 0swaps
ine 12, in <module>
    os.mkdir(pwd + "/surfaces")
OSError: [Errno 17] File exists: '/N/dc2/scratch/brlife/karst-workflows/59dd018db81e0a0024fb1c3f/59de331323cc1400283edc79/surfaces'
0.53user 1.60system 0:37.76elapsed 5%CPU (0avgtext+0avgdata 57252maxresident)k
0inputs+16outputs (0major+15149minor)pagefaults 0swaps
```

I think I've ran brand new job (didn't rerun) so I am not sure why `surfaces` directory exist already..

Note: This issue doesn't happen always. Most jobs finish successfully.

**Comment by kitchell** [comment]
this is strange because it is also set to remove the surfaces folder before running if it does exist. so even if rerunning it should not get this error
