### ISSUE TITLE
Doesn't run on karst

### ISSUE THREAD

**Issue by soichih** [kitchell/app-generatetractsurfaces#6]
This app is failing to run Karst.

```
singularity exec -e docker://lukin0110/docker-vtk-python ./main.py
```

```
Docker image path: index.docker.io/lukin0110/docker-vtk-python:latest
Cache folder set to /gpfs/home/b/r/brlife/Karst/.singularity/docker
Creating container runtime...
chmod: cannot operate on dangling symlink `/tmp/.singularity-runtime.fqTe2T90/lukin0110/docker-vtk-python/etc/ssl/certs/GeoTrust_Universal_CA_2.pem'
WARNING: Non existent bind point (directory) in container: '/N/home'
WARNING: Non existent bind point (directory) in container: '/N/u'
WARNING: Non existent bind point (directory) in container: '/N/dc2'
WARNING: Non existent bind point (directory) in container: '/N/soft'
WARNING: Could not chdir to home: /N/u/brlife/Karst
/.singularity.d/actions/exec: 8: exec: ./main.py: not found
ls: cannot access
```

singularity on Karst runs slightly different from other hosts (carbonate, slurm2). It can't create bind points (like /N/u) if the container doesn't have those directories already existing. I think we should do 1 of following.

1) Steal the Dockerfile used to build iukin0110/docker-vtk-python and build our own container  that includes following at the endo

$ .. everything from the kukin0110/docker-vtk-python Dokerfile ..
$ RUN ldconfig && mkdir -p /N/home /N/u /N/dc2 /N/soft

2) Create a new container that inherits from lukin0110/docker-vtk-python.

$ FROM lukin0110
$ RUN ldconfig && mkdir -p /N/home /N/u /N/dc2 /N/soft

I like 1) better, because it allows us to be more self contained.. as I am not sure who lukin0110 is..

**Comment by kitchell** [comment]
Setting 1 up now.

**Comment by kitchell** [comment]
1 failed, it copies some files into the container that I do not have. so Im trying option 2 now.

**Comment by kitchell** [comment]
2 works now, @soichih can you test with karst?
